export type fontNames =
  | "SUPER_TINY" //10PX
  | "SUPER_TINY_MEDIUM"
  | "SUPER_TINY_SEMI_BOLD"
  | "TINY" //12PX
  | "TINY_MEDIUM"
  | "TINY_SEMI_BOLD"
  | "SMALL" //14PX
  | "SMALL_MEDIUM"
  | "SMALL_SEMI_BOLD"
  | "REGULAR" //16PX
  | "REGULAR_MEDIUM"
  | "REGULAR_SEMI_BOLD"
  | "LARGE" //20PX
  | "LARGE_MEDIUM"
  | "LARGE_SEMI_BOLD"
  | "BIG" //24PX
  | "BIG_MEDIUM"
  | "BIG_SEMI_BOLD";
