export enum fontTypes {
  TINY = "TINY", //12PX
  TINY_MEDIUM = "TINY_MEDIUM",
  TINY_SEMI_BOLD = "TINY_SEMI_BOLD",
  SMALL = "SMALL", //14PX
  SMALL_MEDIUM = "SMALL_MEDIUM",
  SMALL_SEMI_BOLD = "SMALL_SEMI_BOLD",
  REGULAR = "REGULAR", //16PX
  REGULAR_MEDIUM = "REGULAR_MEDIUM",
  REGULAR_SEMI_BOLD = "REGULAR_SEMI_BOLD",
  LARGE = "LARGE", //20PX
  LARGE_MEDIUM = "LARGE_MEDIUM",
  LARGE_SEMI_BOLD = "LARGE_SEMI_BOLD",
  BIG = "BIG", //24PX
  BIG_MEDIUM = "BIG_MEDIUM",
  BIG_SEMI_BOLD = "BIG_SEMI_BOLD",
}

export type fontTypesEnum =
  | "TINY"
  | "TINY_MEDIUM"
  | "TINY_SEMI_BOLD"
  | "SMALL"
  | "SMALL_MEDIUM"
  | "SMALL_SEMI_BOLD"
  | "REGULAR"
  | "REGULAR_MEDIUM"
  | "REGULAR_SEMI_BOLD"
  | "LARGE"
  | "LARGE_MEDIUM"
  | "LARGE_SEMI_BOLD"
  | "BIG"
  | "BIG_MEDIUM"
  | "BIG_SEMI_BOLD";
